baseURL = "https://tonykrev.github.io/"
languageCode = "en-us"
title = "TonyK's Tech Blog"
theme = "loficode"

# GitHub Pages configuration
canonifyURLs = false
relativeURLs = false

# Permalink structure
[permalinks]
  posts = "/posts/:title/"

[params]
  description = "Your site description"

  # Ambient sounds defaults
  [params.ambient_sounds]
    default_volume = 0.5

  # Custom cursor configuration
  [params.cursor]
    enabled = true
    default = "/images/cursor/hello-kitty.png"
    pointer = "/images/cursor/hello-kitty.png"
    hotspot_x = 6
    hotspot_y = 0

  # Thông tin tác giả
  [params.author]
    name  = "Tran Quang Huy"
    image = "/images/avatar.jpg"
    bio   = "Security Researcher | Reverse Engineering"

  # Profile section (theme hỗ trợ)
  [params.profile]
    name   = "Tran Quang Huy"
    tagline = "Your tagline here"
    photo   = "/images/avatar.jpg"

  # Social links
  [params.social]
    github    = "raisingpixels"
    instagram = "https://www.instagram.com/t0nyk_"
    facebook  = "https://www.facebook.com/t0nyK06"
    linkedin  = "your-linkedin-username"
    email     = "tranhuydh81@gmail.com"

# Navigation menu
[[menu.main]]
  name = "Home"
  url  = "/"
  weight = 5

[[menu.main]]
  name = "About"
  url  = "/about/"
  weight = 10

[[menu.main]]
  name = "Archives"
  url  = "/archives/"
  weight = 15

[[menu.main]]
  name = "Achievements"
  url  = "/achievements/"
  weight = 20

