theme = "loficode"

[params]
  description = "Your site description"

  # Thông tin tác giả
  [params.author]
    name  = "Tran Quang Huy"
    image = "/images/avatar.jpg"
    bio   = "Security Researcher | Reverse Engineering"

  # Profile section (theme hỗ trợ)
  [params.profile]
    name   = "Tran Quang Huy"
    tagline = "Your tagline here"
    photo   = "/images/avatar.jpg"

  # Social links
  [params.social]
    github   = "raisingpixels"
    twitter  = "raisingpixels"
    linkedin = "your-linkedin-username"
    email    = "tranhuydh81@gmail.com"
    youtube  = "https://youtube.com/@yourusername"
    instagram = "https://www.instagram.com/t0nyk_"
    facebook  = "https://www.facebook.com/t0nyK06"

# Navigation menu
[[menu.main]]
  name = "About"
  url  = "/about/"
  weight = 10

[[menu.main]]
  name = "Contact"
  url  = "/contact/"
  weight = 20
